[package]
name = "mdwc"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
glob = "0.3"
pdf-extract = "0.6"
regex = "1.7"
zip = "0.6"

[dev-dependencies]
tempfile = "3.3"
